export const Stages = Object.freeze({
    SCHEMA : "00-schemas",
    META : "01-metadata",
    SNAP : "02-snapshots",
    DOCTREE : "03-doctrees",
    DOCCHUNK : "04-doclines",
    DIFF_RAW : "05-diffs-raw",
    DIFF_SPAN : "05-diffs-span",
    DIFF_CLEAN : "05-diffs-clean",
    BRIEF_RAW : "06-brief-raw",
    BRIEF_CLEAN : "06-brief-clean",
    SUMMARY_RAW : "07-summary-raw",
    SUMMARY_CLEAN : "08-summary-clean",
    LABELS : "09-labels",
    CLAIM_RAW : "10-claim-raw",
    CLAIM_CLEAN : "11-claim-clean",
    FACTCHECK_RAW : "12-factcheck-raw",
    FACTCHECK_CLEAN : "13-factcheck-clean",
    JUDGE_RAW : "14-judge-raw",
    JUDGE_CLEAN : "15-judge-clean",
});